{{- if .Values.kserveFrontend.enabled }}
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: {{ .Values.kserveFrontend.serviceName }}
  namespace: {{ include "image-detection-pipeline.namespace" . }}
  labels:
    {{- include "image-detection-pipeline.labels" . | nindent 4 }}
    component: frontend
spec:
  predictor:
    containers:
      - name: kserve-container # Nên đổi tên thành kserve-container để chuẩn hóa với KServe
        image: "{{ .Values.kserveFrontend.image.repository }}:{{ .Values.kserveFrontend.image.tag }}"
        imagePullPolicy: {{ .Values.kserveFrontend.image.pullPolicy }}
        ports:
          - containerPort: {{ .Values.kserveFrontend.containerPort }}
            name: http1
            protocol: TCP
        # Thêm phần này để fix lỗi "quay quay"
        readinessProbe:
          tcpSocket:
            port: {{ .Values.kserveFrontend.containerPort }}
          initialDelaySeconds: 15  
          periodSeconds: 10    
          failureThreshold: 3    
        env:
          - name: BACKEND_URL
            value: 'http://{{ include "image-detection-pipeline.fullname" . }}-backend:{{ .Values.backend.service.port }}'
        resources:
          {{- toYaml .Values.kserveFrontend.resources | nindent 10 }}
{{- end }}

