apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "image-detection-pipeline.fullname" . }}-frontend
  namespace: {{ include "image-detection-pipeline.namespace" . }}
  labels:
    {{- include "image-detection-pipeline.labels" . | nindent 4 }}
    component: frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "image-detection-pipeline.selectorLabels" . | nindent 6 }}
      component: frontend
  template:
    metadata:
      labels:
        {{- include "image-detection-pipeline.selectorLabels" . | nindent 8 }}
        component: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
              protocol: TCP
          env:
            - name: BACKEND_URL
              value: 'http://{{ include "image-detection-pipeline.fullname" . }}-backend:{{ .Values.backend.service.port }}'
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
